from __future__ import annotations

import logging
from pathlib import Path

from fixmate.helpers.config_loader import load_configs


class JustIndexer:
    def __init__(self, config_path: Path | None = None) -> None:
        config_path = config_path or Path("pyproject.toml")
        self._configs = load_configs(config_path, "just_indexer")
        self._output_file_name = self._get_output_file_name()
        self._modules_optional = self._get_modules_optionality()
        self._include_patterns = self._get_include_patterns()
        self._logger = logging.getLogger(__name__)

    def run(self, root_dirs: list[Path | str] | None = None) -> None:
        resolved_root_dirs = [Path(root_dir) for root_dir in (root_dirs or [])]
        generated_files = []

        for root_dir in resolved_root_dirs:
            generated_file = self._generate_index_file(root_dir)
            generated_files.append(generated_file)

        generated_files_str = ", ".join(str(f) for f in generated_files)
        self._logger.info("Generated index files: %s", generated_files_str)

    def _generate_index_file(self, root_dir: Path) -> Path:
        modules = []
        files = self._get_files_to_index(root_dir)

        for file in files:
            name = file.stem
            module_prefix = "mod?" if self._modules_optional else "mod"
            modules.append(f"{module_prefix} {name}")

        header = ["# AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.", "# Generated by just_indexer", ""]

        content = "\n".join([*header, *modules]) + "\n"
        output_path = root_dir / self._output_file_name
        output_path.write_text(content)
        return output_path

    def _get_files_to_index(self, root_dir: Path) -> list[Path]:
        files: set[Path] = set()

        for pattern in self._include_patterns:
            for file in root_dir.glob(pattern):
                if file.is_file():
                    files.add(file)

        return sorted(files)

    def _get_output_file_name(self) -> str:
        value = self._configs.get("output-file-name")
        default_value = "_index.just"
        return value if isinstance(value, str) and value else default_value

    def _get_modules_optionality(self) -> bool:
        value = self._configs.get("modules-optional")
        default_value = True
        return value if isinstance(value, bool) else default_value

    def _get_include_patterns(self) -> list[str]:
        value = self._configs.get("include-patterns")
        default_value = ["[!_]*.just"]

        if not isinstance(value, list):
            return default_value

        sanitized_patterns = [pattern for pattern in value if isinstance(pattern, str) and pattern]
        return sanitized_patterns or default_value
